services:
  service_generator:
    struct: "generators.Service"

  reference_parser:
    struct: "parsers.Reference"
    constructor: "parsers.NewReference"
    arguments:
      - "make(map[string]interface{})"
      - "@yaml_file_reader"

  service_parser:
    struct: "parsers.Service"

  yaml_file_reader:
    struct: "parsers.YamlFileReader"
    constructor: "parsers.NewYamlFileReader"
    arguments:
      - "make(map[string]interface{})"

  test.example_listener:
    struct: "test.ExampleListener"

  test.my_listener:
    struct: "test.MyListener"

listeners:
  show_info:
    - service: "@test.example_listener"
      method: "ShowInfo"
  show_info2:
    - service: "@test.my_listener"
      method: "Show"
