services:
  service_generator:
    struct: "generators.Service"

  listener_generator:
    struct: "generators.Listener"

  reference_parser:
    struct: "parsers.Reference"
    constructor: "parsers.NewReference"
    arguments:
      - "make(map[string]interface{})"
      - "@yaml_file_reader"

  service_parser:
    struct: "parsers.Service"

  yaml_file_reader:
    struct: "parsers.YamlFileReader"
    constructor: "parsers.NewYamlFileReader"
    arguments:
      - "make(map[string]interface{})"

  service_file_writer:
    struct: "domain.FileWriter"
    constructor: "domain.NewFileWriter"
    arguments:
      - "'kernel/services'"
      - "'services.go'"

  container_builder:
    struct: "builder.Container"
    constructor: "builder.NewContainerBuilder"
    arguments:
      - "@yaml_file_reader"
      - "@reference_parser"
      - "@service_parser"
      - "@listener_generator"
      - "@service_generator"
      - "@service_file_writer"

  test.example_listener:
    struct: "test.ExampleListener"

  test.my_listener:
    struct: "test.MyListener"

listeners:
  show_info:
    - service: "@test.example_listener"
      method: "ShowInfo"
  show_info2:
    - service: "@test.my_listener"
      method: "Show"
